[CCC]version=3
[CCC]wifi_coex_time_gap=10
[CCC]ap_coop_mode=1
[CCC]wifi_coex_min_spacing=0x08
[CCC]ch5.antenna_selection=ant0
[CCC]ch9.antenna_selection=ant0
[CCC]alternate_pulse_shape=0x00
ant0.ch5.prf16.ant_delay=16447
ant0.ch5.prf16.tx_power=0x67672F67
ant0.ch5.prf16.pg_count=0
ant0.ch5.prf16.pg_delay=0x26
ant0.ch5.prf64.ant_delay=16462
ant0.ch5.prf64.tx_power=0x67672F67
ant0.ch5.prf64.pg_count=0
ant0.ch5.prf64.pg_delay=0x26
ant0.ch9.prf16.ant_delay=16492
ant0.ch9.prf16.tx_power=0x5F5F2F5F
ant0.ch9.prf16.pg_count=0
ant0.ch9.prf16.pg_delay=0x26
ant0.ch9.prf64.ant_delay=16527
ant0.ch9.prf64.tx_power=0x5F5F2F5F
ant0.ch9.prf64.pg_count=0
ant0.ch9.prf64.pg_delay=0x26
ant0.port=0
ant0.selector_gpio=5
ant0.selector_gpio_value=0
ant1.ch5.prf16.ant_delay=16447
ant1.ch5.prf16.tx_power=0
ant1.ch5.prf16.pg_count=0
ant1.ch5.prf16.pg_delay=0
ant1.ch5.prf64.ant_delay=16462
ant1.ch5.prf64.tx_power=0
ant1.ch5.prf64.pg_count=0
ant1.ch5.prf64.pg_delay=0
ant1.ch9.prf16.ant_delay=16409
ant1.ch9.prf16.tx_power=0
ant1.ch9.prf16.pg_count=0
ant1.ch9.prf16.pg_delay=0
ant1.ch9.prf64.ant_delay=16444
ant1.ch9.prf64.tx_power=0
ant1.ch9.prf64.pg_count=0
ant1.ch9.prf64.pg_delay=0
ant1.port=0
ant1.selector_gpio=5
ant1.selector_gpio_value=1
ant2.ch5.prf16.ant_delay=16450
ant2.ch5.prf16.tx_power=0
ant2.ch5.prf16.pg_count=0
ant2.ch5.prf16.pg_delay=0
ant2.ch5.prf64.ant_delay=16450
ant2.ch5.prf64.tx_power=0
ant2.ch5.prf64.pg_count=0
ant2.ch5.prf64.pg_delay=0
ant2.ch9.prf16.ant_delay=16450
ant2.ch9.prf16.tx_power=0
ant2.ch9.prf16.pg_count=0
ant2.ch9.prf16.pg_delay=0
ant2.ch9.prf64.ant_delay=16450
ant2.ch9.prf64.tx_power=0
ant2.ch9.prf64.pg_count=0
ant2.ch9.prf64.pg_delay=0
ant2.port=1
ant0.ant2.ch5.pdoa_offset=0
ant0.ant2.ch9.pdoa_offset=0
ant1.ant2.ch5.pdoa_offset=0
ant1.ant2.ch9.pdoa_offset=0
ch5.pll_locking_code=0
ch9.pll_locking_code=0
ch5.wifi_coex-enabled=0
ch9.wifi_coex-enabled=0
temperature_reference=85
smart_tx_power=1
auto_sleep_margin=20000
restricted_channels=0xFFFF
[HAL]aoa_restricted_channels=0
[HAL]aoa_capability=0
[HAL]minimum_system_offset_uwbtime0=250
[HAL]ant_sets.ch5.range.tx_ant_set_ranging=6
[HAL]ant_sets.ch5.range.tx_ant_set_nonranging=6
[HAL]ant_sets.ch5.range.rx_ant_set_ranging=6
[HAL]ant_sets.ch5.range.rx_ant_set_nonranging=6
[HAL]ant_sets.ch9.range.tx_ant_set_ranging=6
[HAL]ant_sets.ch9.range.tx_ant_set_nonranging=6
[HAL]ant_sets.ch9.range.rx_ant_set_ranging=6
[HAL]ant_sets.ch9.range.rx_ant_set_nonranging=6
alternate_pulse_shape=0x00
